import { ThemeProvider } from "@/components/theme"
import { ReactQueryProvider } from "@/react-query/provider"
import { ReduxProvider } from "@/redux/provider"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import { Toaster } from "sonner"
import "./global.css"

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "EduPamoja",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={{
      variables: {
        colorPrimary: '#fff',
        colorText: '#ffffff',
        colorTextSecondary: '#9ca3af',
        colorBackground: '#111827',
        colorInputBackground: '#1f2937',
        colorShimmer: 'rgba(255,255,255,0.36)',
        fontFamily: 'Plus Jakarta Sans',
      },
      layout: {
        logoImageUrl: '/logo.png',
        logoPlacement: 'inside',
        socialButtonsPlacement: 'bottom',
        socialButtonsVariant: 'iconButton',
        termsPageUrl: '/terms',
        privacyPageUrl: '/privacy',
      },
      elements: {
        card: {
          boxShadow: '0 0 0 1px rgba(255,255,255,0.1)',
        },
        headerTitle: {
          fontSize: '1.5rem',
          fontWeight: '600',
        },
        headerSubtitle: {
          opacity: 0.8,
        },
      }
    }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${jakarta.className} bg-black`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            <ReduxProvider>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </ReduxProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
